### ISSUE TITLE
Unable to initialize a reader on iPad Air 2

### ISSUE THREAD

**Issue by ashfurrow** [CardFlight/cardflight-ios#21]
Looks nearly identical to #19 except the "workaround" involving breakpoints isn't working. Console log is:

```
2015-02-26 19:08:55.467 Kiosk[864:2963634] CardFlight -[CFTReader swipeTimeoutDuration:] Duration:0
2015-02-26 19:08:55.740 Kiosk[864:2963634] CardFlight -[CFTReader uniMagAttached:] call to readerIsAttached
2015-02-26 19:08:56.743 Kiosk[864:2963634] CardFlight -[CFTReader uniMagConnectionStarting:] call to readerIsConnecting
2015-02-26 19:09:05.409 Kiosk[864:2963634] -[CFTReader uniMagConnectionTimeout:] - NSConcreteNotification 0x17465db50 {name = uniMagTimeoutNotification}
2015-02-26 19:09:05.410 Kiosk[864:2963634] CardFlight -[CFTReader uniMagConnectionTimeout:] call to readerIsConnected
```

iPad model number is MH2U2LL/A (includes cellular). Running iOS 8.1.3 (12B466). 

Error description:

```
Connecting to CardFlight timed out. Please try again
```

I've tried multiple readers on multiple iPads; all readers work fine on older models and all fail on the iPad Air 2.

Installed version 1.9.2 of the library via CocoaPods. Please let me know anything else I can provide to help diagnose this issue. We have a time-sensitive even happening this weekend that we need to use the card readers for.

**Comment by hokiewalrus** [comment]
There is nothing specific to an iPad Air 2 that would keep it from working with our readers. In fact we have an Air 2 as part of our internal testing suite and I was just using it yesterday without issue.

Has a reader ever connected with the iPad? In situations like the one you describe where everything works except with one specific device the issue is usually with the device, not with our SDK or readers.

**Comment by ashfurrow** [comment]
Hmm. That's very odd. This is not a problem that we're seeing with a specific device; this is a problem we're seeing on _all_ iPad Air 2's (identical builds run fine on older models). I'll try resetting to factory settings and get back to you.

**Comment by ashfurrow** [comment]
Could this be specific to the 3G models? I'll test on a non-3G device and let you know.

**Comment by hokiewalrus** [comment]
The version we have here has cellular connectivity, and we have several customers using iPad's (including Air 2's) and have never had an issue with these models since releasing 1.9.2.

The reason for the breakpoint workaround was the new iOS devices were responding to connection events before the readers had been initialized, so we had to add an artificial delay in version 1.9.2 to give the readers a chance to be ready to receive events. That is the only issue we are aware of that could effect all devices of a particular model.

**Comment by ashfurrow** [comment]
Ok thanks for the quick follow-up. I'll let you know if a factor reset works. Your devices are running 8.1.3?

**Comment by hokiewalrus** [comment]
Yup, 8.1.3

**Comment by ashfurrow** [comment]
I performed a factory reset, granted microphone access, and it worked! I'm going to do some more troubleshooting at get back to you if I can pinpoint the source of our error.

**Comment by hokiewalrus** [comment]
Great! Glad that got it working. And yes, please let us know if you figure out what caused the error.

**Comment by ashfurrow** [comment]
Will do. It could be related to CocoaPods – we're using 0.36 Beta 2, which uses frameworks, but the CardFlight SDK has a static library bundled with it (if I understand correctly). So maybe CocoaPods wasn't smart enough about replacing the `.a` file when I updated the pod; deleting the `Pods` folder and re-installing seemed to work. 

I'll try and reproduce and let you know.

**Comment by ashfurrow** [comment]
I'm not sure why or how this problem occurred; I've tried to reproduce the same situation and CocoaPods updates the library fine. It was probably me rushing through many different possible fixes and not verifying the update thoroughly enough. I apologize for the fix and thank you for your prompt response.

**Comment by hokiewalrus** [comment]
Probably just a glitch in the matrix, it's entirely possible that CocoaPods experienced a one-time error that would be impossible to reproduce.

Glad everything got sorted though. Let us know if you have any more issues.
