### ISSUE TITLE
CocoaPods with Swift support

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [CardFlight/cardflight-ios#54]
Adding CardFlight SDK to a Swift project via CocoaPods is broken.
- If you use the `use_frameworks!` flag in the `Podfile`, you get a **No such module** error when you build the project.
- If you go the bridging header way, it still won't work. I get a bunch of **Unknown type name**, **Use of undeclared identifier**, **Expected a type** errors when building.

Swift is gaining more and more traction every day. So Swift support is essential.

**Comment by hokiewalrus** [comment]
Swift support is definitely on our roadmap and we are working on getting that out as soon as possible.

**Comment by brblakley** [comment]
@Isuru-Nanayakkara I haven’t done a full CardFlight implementation with Swift but was able to get it building and made a simple `CFTSessionManager` call. I used the second technique you mentioned (i.e. using a bridging header). To work around the various compiler errors (e.g. “Use of undeclared identifier 'EMVMessage_UNKNOWN'”), I imported Foundation before importing CardFlight. My guess is that CardFlight depends on Foundation but doesn’t import it itself. In other words, my bridging header looks like this:

```
#import <Foundation/Foundation.h> // CardFlight seems to depend on Foundation but doesn't import it on its own.
#import "CardFlight.h"
```

@hokiewalrus Should I file a separate issue for the compiler errors that show up when Foundation hasn’t been imported yet (since it happens in Objective-C as well and this issue is about Swift support)?

**Comment by rashmiPatil10** [comment]
@hokiewalrus I am facing same issue. getting error <CardFlight/CardFlight.h> file not found in my bridging header. when I am using cocoa pods to install SDK. Is any way to implement CardFlight using swift.

**Comment by hokiewalrus** [comment]
Our brand new release of CardFlight, version 4 includes greatly enhanced support for Swift: https://github.com/CardFlight/cardflight-v4-ios
