### ISSUE TITLE
CFTReaderState - ReaderState_WAITING_FOR_CONNECT

### ISSUE THREAD

**Issue by sanketfirodiya** [CardFlight/cardflight-ios#58]
If I get this state even after connecting the card reader, does it mean the card reader has a problem and I should replace it?
This is happening in code that was working perfectly fine and suddenly I started seeing the issue. Upon connecting the device to console, I read it in the logs. 
So there's definitely no code change from me causing it.

It also happened a couple of weeks and it got fixed when I just replaced the card reader.

**Comment by hokiewalrus** [comment]
@sanketfirodiya This issue indicates that the reader is not performing any communication with the SDK. This can be due to a problem with the reader, either a dead battery or a fault with the hardware itself.

Ensure that the reader is fully charged (but not currently charging) and attempt another connection. If it continues to fail please contact support@cardflight.com for a replacement.
